### ISSUE TITLE
v0.3.0 checklist

### ISSUE THREAD

**Issue by rbalicki2** [isographlabs/isograph#192]
v0.3.0 checkilist:

## docs

- [x] re-read the docs
- [x] add docs about { parameters }
- [x] update docs about pagination
- [x] document validations/variable usage
- [x] document loadable fields and refetching
- [x] document `useImperativeReference`
- [x] document fetch policies
- [x] asFoo fields
- [x] putting it all together: 3D

## features

- [x] pagination hooks with initial state
- [x] window.__LOG fix
    - [x] ~audit what log messages we actually want~ edit: MEH
- [x] basic fetch policy (i.e. ability to skip fetching if data is present in store)
  - [x] fetch policy in loadable fields
- [x] key allowed in props
    - [x] fix regression where `additionalFields` is always required
- [x] interfaces and `asFoo` fields
