### ISSUE TITLE
[epic] Inline fragments

### ISSUE THREAD

**Issue by rbalicki2** [isographlabs/isograph#230]
## Overall thoughts

Server linked fields and inline fragments are two variants of the same struct. Ideally, Isograph doesn't know about the difference between these, and the only difference is in the "GraphQL layer", which includes query generation. In the long run, it would **not** include merged selection set generation!

A merged selection set has three variants: Scalar + Linked + InlineFragment. Instead, it should have two variants: Scalar + Linked, and each linked field should include information on whether it is a linked field or inline fragment.

The GraphQL-specific query and normalization AST generation part should understand how to specially handle inline fragments.

Also, in the long run, there should be two types of schema server fields: Scalar and Linked, as in `Schema` should have `server_scalars: Vec<...>` and `server_pointers: Vec<...>` (naming TBD). Splitting linked and scalar fields is not part of this task, unless necessary.

We do not need to do everything listed above as part of this task.

## Tasks

- [ ] Add a `variant: FieldVariant` field to `SchemaServerField`. This should encode whether it's a linked field or inline fragment. All existing fields should have `FieldVariant::LinkedField`
- [ ] Create `asConcreteType` fields that have `FieldVariant::InlineFragment`
- [ ] Modify create_merged_selection_set to look at the variant and create inline fragments or linked fields

More TBD

**Comment by rbalicki2** [comment]
I think this is done!
